const modalItems = [
  {
    id: 1,
    title: 'Šicové z Drahenic',
    desc: 'Šicové byli starým vladyckým rodem, který se prvně připomíná počátkem 15. století na Prácheňsku. Pocházeli ze vsi Drahenice a mezi prvními jsou uváděni Jan z Drahenic se svými syny Janem a Albertem. Jan pak vlastní Zalužany a Albert kupuje roku 1453 ves Laszko. Albert později získává od svého bratra Zalužany a od roku 1461 zastává úřad místopurkrabího na Karlštejně. Byl ženatý  s Barborou, rozenou ze Všechlap, s kterou měl syna Mikuláše. Z dalších menších statků, které rod vlastnil, lze jmenovat např. Zbenice, Smolety, Suchou, Nedanice atd. Po porážce stavovského povstání na Bílé hoře roku 1620, je rod odsouzen ke ztrátě dvou třetin majetku. Poslední známý člen rodu Mikuláš Šic je připomínán roku 1650 v Drážďanech. Po tomto datu stopa tohoto  rodu mizí.'
  },
  {
    id: 2,
    title: 'Opršalové z Jetřichovic',
    desc: 'Opršalové z Jetřichovic byli starým vladyckým rodem, který  pocházel ze vsi Jetřichovice na Sedlčansku. První zmínka o nich je z poloviny 15. století. Tehdy se připomíná Jan a Matěj z Jetřichovic. Opršalové ještě vlastní několik okolních vesnic –např. Smolety a Zbynice. Poslední zmínka o tomto rodu je z druhé poloviny sedmnáctého století, kdy se stopa ztrácí na Moravě.'
  },
  {
    id: 3,
    title: 'Bukovanští z Bukovan',
    desc: 'První zmínka o vladycké rodině Bukovanských z Bukovan pochází z roku 1414, kdy se na Obdenících připomínají bratři Bohuslav, Oldřich a Sigmund Bukovanští Pintové z Bukovan. Predikát Pintové měli podle konve – pinty, kterou měli ve svém erbu. Další zmínky pocházejí z roku 1481, kdy Jindřich Pinta kupuje ves Živonice, pak Jan Bukovanský drží v letec 1534 – 1571 kromě Bukovan a Živonic také Újezdec, Kraštice, Zbynice atd.Za manželku měl Lidmilu Nebílovskou z Drahobuze, s kterou měl syna Přibíka. Ten po otci drží Zbynice, ke kterým přikoupil ještě Kozarovice, Nestrašovice a Těchničský Újezd. Byl ženat s Justínou Vamberskou z Rohatec, s kterou měl třináct dětí.Přibík umírá roku 1601.První z jeho synů Jindřich se dal na vojenskou dráhu a roku 1596 padl v bitvě u Jagru v boji proti Turkům. Přibíka přežilo jen šest jeho dětí.Dcera Johanka se vdala za Viléma Chanovského z Dlouhé Vsi,Regina se stala manželkou Václava staršího Vratislava z Mitrovic.Jan po otcově smrti dědí část Bukovan, ke kterým roku 1604 přikoupil ještě část Lešetic.    Oženil se s Eliškou Smrčkovou z Mnichu, čímž se stal i spoludržitelem statku Krašovice. Zemřel bezdětný roku 1619 a veškeré majetky odkazuje své manželce.Adam kupuje roku 1609 Suchomasty, o rok později Radouš.Za podporu stavovského povstání mu byl tento majetek zkonfiskován.Jaroslav sedí na Řeteči, než roku 1616 kupuje Žihobeč.I on je po porážce českých stavů odsouzen ke ztrátě majetku.Václav byl po Bílé hoře osvobozen a od roku 1622 sedí na Bukovanech, kde roku 1632 zemřel.Byl ženatý s Alenou Saloménou Černínovou z Chudenic, která Bukovanský statek dědí.Měli spolu dvě dcery Maxmiliánu Alžbětu,která se provdala za Jiřího Václava Černína z Chudenic a Annu Ludmilu,manželku Kašpara Zdeňka Kaplíře ze Sulevic.Jan a Zikmund umírají ještě před Václavem bez mužských potomků.Tím prakticky vymírá hlavní linie Pintů z Bukovan.Existovala totiž ještě vedlejší zchudlá větev, která se zmiňuje naposledy roku 1801, kdy sourozenci Jan Jáchym, Antonie a Inocencie prodávají statek Horní Terešov.'
  },
  {
    id: 4,
    title: 'Vlkové z Kvítkova',
    desc: 'Vlkové z Kvítkova odvozovali svůj predikát od tvrze Kvítkov na  Litoměřicku. Roku 1470 se připomíná Jan Vlk z Kvítkova, který sedí na Čakovicích. Po něm na Čakovicích sedí sestry Barbora,  Johanka a Mandalena z Kvítkova následně další Jan Vlk z  Kvítkova, který zde umírá roku 1546 a ves přechází na jeho syna  Václava. V tomto období se také připomínají sourozenci Jiří,  Jindřich, Alena a Mandalena, kteří roku 1548 prodávají Rokytnici Janovi Lickovi z Riesenburka. V tomto století jsou kusé zmínky i  o dalších členech tohoto rodu, kteří vlastní nejrůznější drobné    statky – Smědovice, Velenice, Radujeň, Štědrov, Vlčkovice atd. Roku 1609 kupuje Barbora, rozná z Mitrovic, vdova po Adamovi Vlkovi z Kvítkova, pro svého nezletilého syna Jana od Adama  Bukovanského z Bukovan statek Zbenice. Když Jan dospěl, statek prodává Vilému Šléglovskému ze Sicendorfu a kupuje Zvířetice. Protože se ale účastnil stavovského povstání proti Ferdinandovi II. Habsburskému, je mu majetek zkonfiskován. Po roce 1620 je připomínán z tohoto rodu Jan Vlk z Kvítkova, který odmítl přejít na katolickou víru a odchází ze země. Zde měl se svou ženou Johanou, rozenou Dobřenskou z Dobřeni syna Jana Theodora. Ten si zde bere za manželku Zuzanu Sidonii, rozenou Skrbenskou z Hříště, s kterou má syna Maxmiliána Arnošta,který sloužil v císařské armádě. Umírá roku 1721 v Opavě a s ním vymírá celý tento rod.'
  },
  {
    id: 5,
    title: 'Čejkové z Olbramovic',
    desc: 'První zmínka o tomto rodu pochází z 15. století, kdyse Čejkové  oddělili od ostatních vladyckých rodin s přídomkem z Olbramovic.V poměrně krátkém čase se rozrostli do celé řady odnoží, které sídlili v Čechách i na Moravě,na řadě drobných statcích. Jen v Čechéch žilo počátkem 17. století devět rodin Čejků z Olbramovic. Nejzámožnější z nich byla kácovská linie, z které pocházeli bratři, Václav Čejka sedící na Kácově a Jan Čejka na Ratajích. Jan Čejka se po sňatku s uherskou šlechtičnou Voršilou Lorantovou z Inky přestěhoval na Moravu a nastoupil zde politickou kariéru. Za stavovského povstání stál na straně rebelů a po prohře na Bílé hoře byl uvězněn na Špilberku. Zde byl odsouzen k smrti, ale na přímluvu přátel mu byl rozsudek změněn na doživotí a později zcela zrušen. Krátce nato ale Jan Čejka umírá. Za Václava Čejky z Olbramovic se Kácov stal střediskem rozsáhlého panství, neboť Václav skupoval okolní statky. V rozšiřování panství pokračoval i Václavův syn Karel Čejka, kterému Kácov patřil od r. 1600 až do pobělohorských  konfiskací. Česká část rodu se postupně z pobělohorských persekucí vzpamatovala a roku 1748 získává hraběcí titul.   Poslední zmínka o tomto rodu je z 19. století, kdy zchudl a byl vymazán z evidence české šlechty.'
  },
  {
    id: 6,
    title: 'Schwarzenberkové',
    desc: 'Schwarzenberkové jsou původem franský šlechtický rod, poprvé  doložený roku 1172. Původní název rodu ale zněl Seinsheim. Až když Erkinger ze Seinsheimu zakoupil na přelomu 14. a 15.století panství Schwarzenberk, začal se psát ze Schwarzenberka.V letech 1420 – 1421 se účastnil válečných výprav proti husitům, začež obdržel od krále Zikmunda do zástavy města Žatec, Kadaň a Beroun a roku 1429 je povýšen do stavu svobodných pánů ze Schwarzenberku. Roku 1599 se Adolf Schwarcwnberg účastnil tažení proti Turkům, kde získal po vítězné bitvě u Rábu titul říšského hraběte a polepšení erbu o hlavu Turka, kterému krkavec vyklovává oko. Roku 1654 získávají Schwarcenberkové v Čechách inkolát / obdoba dnešního občanství, právo vlastnit pozemky /.Prvním majetkem, který v Čechách získávají je panství Třeboň /1660/ a Hluboká nad Vltavou. Rozsáhlý majetek získávají zejména v jižních a severních Čechách, kde kupují např. Český Krumlov, již zmíněnou Hlubokou nad Vltavou, Netopíce, Prachatice, Orlík atd. Před rokem 1918 patřili Schwarzenbekové k nejbohatším v Evropě. V roce 1947 byl znárodněn majetek hlubocké větve  Schwarzenberků o dva roky později museli představitelé orlické  větve uprchnou z Československa. Hlavním představitelem rodu je v současnosti syn knížete Karla VI. Karel Schwarzenberg.'
  },

];

export default modalItems;
